---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: monitoring-ui
  namespace: kube-prometheus-stack
spec:
  parentRefs:
    - name: gateway-internal
      namespace: network
      sectionName: https
  hostnames:
    - "monitoring.${DOMAIN}"
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /alertmanager
      backendRefs:
      - name: kube-prometheus-stack-alertmanager
        port: 9093
    - matches:
      - path:
          type: PathPrefix
          value: /prometheus
      backendRefs:
      - name: kube-prometheus-stack-prometheus
        port: 9090
