---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-config.yml
  - external-secret.yml
  - helm.yml
  - http-route.yml
  - namespace.yml
  - replication-source.yml

configMapGenerator:
  - name: kube-prometheus-stack-helm-values
    files:
      - base-values.yml=values.yml

configurations:
  - kustomizeconfig.yml
