---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prometheus-kube-prometheus-stack
spec:
  sourcePVC: prometheus-kube-prometheus-stack-db-prometheus-kube-prometheus-stack-0
  trigger:
    schedule: 0 * * * *
  kopia:
    accessModes:
      - ReadWriteOnce
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    parallelism: 2
    repository: prometheus-volsync-secret
    retain:
      hourly: 24
      daily: 7
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    moverAffinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: storage
                  operator: In
                  values:
                    - "true"
