---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-repo.yml
  - controlplane-repo.yml
  - hashicorp-repo.yml
  - jetstack-repo.yml
  - longhorn-repo.yml
  - prometheus-community-repo.yml
