---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - charliemaiors-repo.yml
  - cilium-repo.yml
  - controlplane-repo.yml
  - external-dns-repo.yml
  - external-secrets-repo.yml
  - flux-iac-repo.yml
  - goauthentik-repo.yml
  - jetstack-repo.yml
  - jkroepke-repo.yml
  - longhorn-repo.yml
  - prometheus-community-repo.yml
