ingress:
  enabled: true

global:
  nodeSelector:
    storage: enabled

longhornManager:
  nodeSelector:
    storage: enabled

longhornDriver:
  nodeSelector:
    storage: enabled

metrics:
  serviceMonitor:
    enabled: false

defaultSettings:
  systemManagedComponentsNodeSelector: "storage:enabled"