global:
  nodeSelector:
    storage: "true"

longhornManager:
  nodeSelector:
    storage: "true"

longhornDriver:
  nodeSelector:
    storage: "true"

metrics:
  serviceMonitor:
    enabled: true

defaultSettings:
  systemManagedComponentsNodeSelector: "storage:true"