ingress:
  enabled: true
  ingressClassName: cilium
  path: /
  host: ""
  annotations:
    io.cilium/lb-ipam-ips: "10.0.20.202"

global:
  nodeSelector:
    storage: "true"

longhornManager:
  nodeSelector:
    storage: "true"

longhornDriver:
  nodeSelector:
    storage: "true"

metrics:
  serviceMonitor:
    enabled: false

defaultSettings:
  systemManagedComponentsNodeSelector: "storage:true"