---
- name: Download Helm signing key
  ansible.builtin.get_url:
    url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
    dest: /tmp/gpgkey
    owner: root
    group: root
    mode: "0644"

- name: Dearmor Helm signing key
  ansible.builtin.shell: |
      gpg --dearmor < /tmp/gpgkey > /usr/share/keyrings/helm.gpg
  changed_when: false
  no_log: true

- name: Add Helm apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" # yamllint disable-line rule:line-length
    filename: helm-stable-debian
    state: present
