---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garage

resources:
  - ../../base

configMapGenerator:
  - name: garage-helm-values
    behavior: merge
    files:
      - overlay-values.yml=values.yml

patches:
- target:
    group: helm.toolkit.fluxcd.io
    kind: HelmRelease
    name: garage
  path: helm-patch.yml
