---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: postgres-password-gen
  namespace: authentik
spec:
  length: 32
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-password
  namespace: authentik
spec:
  target:
    template:
      type: Opaque
      data:
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: postgres-password-gen
