---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authentik-key-gen
  namespace: authentik
spec:
  length: 50
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: postgres-password-gen
  namespace: authentik
spec:
  length: 32
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  target:
    template:
      type: Opaque
      data:
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .postgres_pass }}"
        AUTHENTIK_SECRET_KEY: "{{ .authentik_key }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: authentik-key-gen
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: postgres-password-gen
