---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: amazon-eks-pod-identity-webhook
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: amazon-eks-pod-identity-webhook
      version: 2.5.7
      sourceRef:
        kind: HelmRepository
        name: jkroepke
        namespace: flux-system
  releaseName: amazon-eks-pod-identity-webhook
  targetNamespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: amazon-eks-pod-identity-webhook-helm-values
    valuesKey: base-values.yml
