---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - helm.yml

configMapGenerator:
  - name: alloy-helm-values
    files:
      - base-values.yml=values.yml

configurations:
  - kustomizeconfig.yml
