$ANSIBLE_VAULT;1.1;AES256
66353739613730396632656662623138376536393963646239626161326339653662326264333964
6238653437306237303639633834313537383533636232620a663566396666343464383265623762
36386331636637643538313466346530313334376633363237643261613238393066373834326332
3637393563366638380a333662633337663537313831616631386531363430636361623539323561
39656139653037353732353262353939396661373663353931623734356635326663
