---
k3s_config_dir: "/etc/rancher/k3s"
k3s_config_file: "{{ k3s_config_dir }}/config.yaml" # Keep this a .yaml file! Not .yml!
k3s_kubeconfig_file: "{{ k3s_config_dir }}/k3s.yaml"
k3s_token_file: "{{ k3s_config_dir }}/cluster-token"

k3s_state_dir: "/var/lib/rancher/k3s"
k3s_cert_dir: "{{ k3s_state_dir }}/server/tls"
