---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: client-id
      remoteRef:
        key: k3s/authentik/applications/grafana
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: k3s/authentik/applications/grafana
        property: client-secret
