---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

resources:
  - ../../base

configMapGenerator:
  - name: authentik-helm-values
    behavior: merge
    files:
      - overlay-values.yml=values.yml

patches:
- target:
    group: helm.toolkit.fluxcd.io
    kind: HelmRelease
    name: authentik
  path: helm-patch.yml
