---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm.yml
  - namespace.yml

configMapGenerator:
  - name: flux-operator-helm-values
    files:
      - base-values.yml=values.yml

configurations:
  - kustomizeconfig.yml
