---
domain: youriulbri.ch
home_domain: "home.{{ domain }}"
cidr_block: 10.0.0.0/16

mail: youri.ulbrich@web.de

system_timezone: Europe/Berlin

cluster_ip: 10.0.20.10
cluster_port: 6443
vault_dns: "vault.{{ home_domain }}"
