---
ntp_device_tty: "ttyAMA0"
ntp_device_baud: "115200"

ntp_gpsd_devices: "/dev/{{ ntp_device_tty }} /dev/pps0"
ntp_gpsd_options: "-n -s {{ ntp_device_baud }} --badtime"
ntp_gpsd_daemon: "true"

ntp_satpulse_enabled: true
ntp_satpulse_version: "0.1-pre-20250930"
ntp_satpulse_proxy_port: 321
ntp_satpulse_survey_time: 3600 # 1 hour
ntp_satpulse_survey_acc: 5.0
