---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alloy
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: alloy
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: kube-prometheus-stack
    - name: loki
  path: ./k8s/platform/alloy/overlays/prod
  prune: true
  wait: true
