---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: amazon-eks-pod-identity-webhook
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
    - name: prometheus-operator-crds
  path: ./k8s/platform/amazon-eks-pod-identity-webhook/overlays/prod
  prune: true
  wait: true
