---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: authentik
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-config
    - name: rook-ceph-cluster
    - name: tofu-controller-namespaces
  path: ./k8s/platform/authentik/app/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-tf
  namespace: flux-system
spec:
  interval: 30m
  retryInterval : 2m
  timeout: 5m
  targetNamespace: authentik
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: authentik
    - name: tofu-controller
  path: ./k8s/platform/authentik/tf/overlays/prod
  prune: true
  wait: true
  healthCheckExprs:
    - apiVersion: infra.contrib.fluxcd.io/v1alpha2
      kind: Terraform
      current: status.conditions.exists(e, e.type == 'Ready') && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      failed: status.conditions.exists(e, e.type == 'Ready') && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
