---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/platform/external-secrets/app/overlays/prod
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets
  path: ./k8s/platform/external-secrets/config/overlays/prod
  prune: true
  wait: true
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      current: status.conditions.exists(e, e.type == 'Ready') && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      failed: status.conditions.exists(e, e.type == 'Ready') && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
