---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/platform/external-secrets/overlays/prod
  prune: true
  wait: true
  dependsOn:
    - name: vault
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
