---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator-operator
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/platform/flux-operator/operator/overlays/prod
  prune: true
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: flux-operator
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator-instance
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-operator-operator
  path: ./k8s/platform/flux-operator/instance/overlays/prod
  prune: true
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: flux-instance
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tofu-controller-namespaces
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/platform/flux-operator/tofu-controller-namespaces/overlays/prod
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: amazon-eks-pod-identity-webhook
    - name: external-secrets-config
  path: ./k8s/platform/flux-operator/tofu-controller/overlays/prod
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator-webui
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: authentik-tf
    - name: flux-operator-operator
    - name: gateway
  path: ./k8s/platform/flux-operator/webui/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
