---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: grafana
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/platform/grafana/operator/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-instance
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: grafana
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: alloy
    - name: authentik-tf
    - name: kube-prometheus-stack
    - name: loki
    - name: network
  path: ./k8s/platform/grafana/instance/overlays/prod
  prune: true
  wait: true
  healthCheckExprs:
    - apiVersion: grafana.integreatly.org/v1beta1
      kind: Grafana
      current: status.conditions.exists(e, e.type == 'Ready') && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      failed: status.conditions.exists(e, e.type == 'Ready') && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
