---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: grafana
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-config
  path: ./k8s/platform/grafana/operator/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-instance
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: grafana
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: alloy
#    - name: authentik-tf
#    - name: gateway
    - name: kube-prometheus-stack
    - name: loki
  path: ./k8s/platform/grafana/instance/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
