---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopia
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kopia
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: volsync
  path: ./k8s/platform/kopia/overlays/prod
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables