---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - amazon-eks-pod-identity-webhook.yml
  - authentik.yml
  - cert-manager.yml
  - cilium.yml
  - external-dns.yml
  - external-secrets.yml
  - flux-operator.yml
  - garage.yml
  - gateway.yml
  - kube-prometheus-stack.yml
  - longhorn.yml
  - tofu-controller.yml
