---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy.yml
  - amazon-eks-pod-identity-webhook.yml
  - authentik.yml
  - cloudnative-pg.yml
  - rook-ceph.yml
  - cert-manager.yml
  - cilium.yml
  - external-dns.yml
  - external-secrets.yml
  - flux.yml
  - grafana.yml
  - kube-prometheus-stack.yml
  - network.yml
  - loki.yml
  - snapshot-controller.yml
