---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: tempo
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-config
    - name: rook-ceph-cluster
  path: ./k8s/platform/tempo/overlays/prod
  prune: true
  wait: true
