---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia-maintenance-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    template:
      data:
        KOPIA_FS_PATH: /repository
        KOPIA_REPOSITORY: filesystem:///repository
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
  data:
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: k3s/kopia
        property: password
