---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia-password
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: k3s/kopia
        property: password
