---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password-gen
spec:
  length: 32
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: kopia-password
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: password-gen
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: k3s/kopia
          property: password
