---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik-db-schema
spec:
  name: authentik
  cluster:
    name: postgres18
  owner: authentik
  extensions:
    - name: pg_trgm
      schema: public
