---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgress-superuser-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: k3s/postgres/credentials
        property: superuser_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: k3s/postgres/authentik/credentials
        property: username
    - secretKey: password
      remoteRef:
        key: k3s/postgres/authentik/credentials
        property: password
