---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password-gen
  namespace: cloudnative-pg
spec:
  length: 32
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: postgress-superuser-password
  namespace: cloudnative-pg
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: password-gen
  template:
    type: Opaque
    data:
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: k3s/postgres/credentials
          property: superuser_password
