kubeProxyReplacement: true

k8sServiceHost: localhost
k8sServicePort: 6443 # get this from ansible?

hubble:
  enabled: false

externalIPs:
  enabled: true

nodePort:
  enabled: true

loadBalancer:
  algorithm: maglev

envoy:
  enabled: false

ipam:
  operator:
    clusterPoolIPv4PodCIDRList: "10.42.0.0/16" # k3s default range

rollOutCiliumPods: true