kubeProxyReplacement: true

# get these from ansible?
k8sServiceHost: 10.0.20.10
k8sServicePort: 6443

hubble:
  enabled: false

externalIPs:
  enabled: true

nodePort:
  enabled: true

loadBalancer:
  algorithm: maglev

envoy:
  enabled: false

l2announcements:
  enabled: true

ipam:
  operator:
    clusterPoolIPv4PodCIDRList: "10.42.0.0/16" # K3s default range

rollOutCiliumPods: true

gatewayAPI:
  enabled: false