---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  kustomize.toolkit.fluxcd.io/substitute: disabled

resources:
  - coredns-mixin-rules.yml
  - etcd-mixin-rules.yml
  - grafana-mixin-rules.yml
  - kubernetes-mixin-rules.yml
  - node-exporter-mixin-rules.yml
  - prometheus-mixin-rules.yml
  - prometheus-operator-mixin-rules.yml
