---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: youriulbri.ch-tls
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: youriulbri.ch-tls
    creationPolicy: Orphan
    template:
      type: kubernetes.io/tls
      metadata:
        annotations:
          cert-manager.io/alt-names: "*.youriulbri.ch,youriulbri.ch"
          cert-manager.io/certificate-name: youriulbri-ch
          cert-manager.io/common-name: youriulbri.ch
          cert-manager.io/ip-sans: ""
          cert-manager.io/issuer-group: ""
          cert-manager.io/issuer-kind: ClusterIssuer
          cert-manager.io/issuer-name: letsencrypt-issuer
          cert-manager.io/uri-sans: ""
        labels:
          controller.cert-manager.io/fao: "true"
  dataFrom:
    - extract:
        key: youriulbri.ch-tls
