---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: youriulbri.ch-tls
spec:
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: youriulbri.ch-tls
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: k3s/youriulbri.ch-tls
          property: tls.crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: k3s/youriulbri.ch-tls
          property: tls.key
