---
vault_packages:
  - opensc
  - python3-hvac

vault_version: 2.4.1
vault_key_label: "vault1"

vault_cert_path: ""
vault_cert_key_path: ""

vault_ca_lease_ttl: "87660h"
vault_int_ca_lease_ttl: "26280h"
