---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-oauth-secret
  namespace: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: github_client_id
      remoteRef:
        key: k3s/authentik/github
        property: client-id
    - secretKey: github_client_secret
      remoteRef:
        key: k3s/authentik/github
        property: client-secret
