---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: k3s/authentik/credentials
        property: secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-password
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: k3s/authentik/credentials
        property: postgres_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-bootstrap-token
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
      remoteRef:
        key: k3s/authentik/credentials
        property: token
