---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yml
#  - namespace.yml
  - helm.yml
  - push-secret.yml

configMapGenerator:
  - name: authentik-helm-values
    files:
      - base-values.yml=values.yml

configurations:
  - kustomizeconfig.yml
