---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authentik-key-gen
  namespace: authentik
spec:
  length: 32
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: postgres-password-gen
  namespace: authentik
spec:
  length: 32
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authentik-token-gen
  namespace: authentik
spec:
  length: 32
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: authentik-key-gen
  template:
    type: Opaque
    data:
      secret_key: "{{ .password }}"
  data:
    - match:
        secretKey: secret_key
        remoteRef:
          remoteKey: k3s/authentik/credentials
          property: secret_key
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-postgres-password
  namespace: authentik
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: postgres-password-gen
  template:
    type: Opaque
    data:
      postgres_password: "{{ .password }}"
  data:
    - match:
        secretKey: postgres_password
        remoteRef:
          remoteKey: k3s/authentik/credentials
          property: postgres_password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-bootstrap-token
  namespace: authentik
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: authentik-token-gen
  template:
    type: Opaque
    data:
      token: "{{ .password }}"
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: k3s/authentik/credentials
          property: token
