---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-route53-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 45m
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: aws/creds/cert-manager-role
        property: access_key
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: aws/creds/cert-manager-role
        property: secret_key
