---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: bucket-admin-credentials
spec:
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: rook-ceph-object-user-ceph-objectstore-admin
  data:
    - match:
        secretKey: AccessKey
        remoteRef:
          remoteKey: k3s/rook/objectstore-admin-credentials
          property: access_key
    - match:
        secretKey: SecretKey
        remoteRef:
          remoteKey: k3s/rook/objectstore-admin-credentials
          property: secret_key
