---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: home-operations-volsync
  namespace: flux-system
spec:
  url: oci://ghcr.io/home-operations/charts-mirror/volsync-perfectra1n
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: "0.18.2"
