---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s-labs-repo.yml
  - grafana-operator-repo.yml
  - home-operations-volsync-repo.yml
  - snapshot-controller-repo.yml
