---
aws_access_key_id: "{{ vault_aws_access_key_id }}"
aws_secret_access_key: "{{ vault_aws_secret_access_key }}"
vault_admin_secret_id_gen_token: "{{ vault_vault_admin_secret_id_gen_token }}"
vault_ansible_secret_id_gen_token: "{{ vault_vault_ansible_secret_id_gen_token }}"
