$ANSIBLE_VAULT;1.1;AES256
32383066636661386338613433646262363730363562636538363631666533313330643666343335
6633643137383362663437343033656330323836626238320a336664623362353236346331393866
65373734323166396538643865613731343138313837616438306265386337633330363733653561
6230656435366532630a376339613930616436373734613336656336316139346466653063313261
38636264353061373565346331363662626639346266616136643430613061303234326539323165
64663735633365333563366162336636306230653864333834643564306630626132393134376535
34336165323163643365336262353065376332306264623136306164343237363737333930616137
37653333366235393938653064356462386661303537316466636264363162313665333465663734
39626235653931346465363236623063653963383839663665666135346639396133613964346261
63373238353132306164656536653764623865663337613039323036363062626364373337326461
36376663353063303130366438363536663230633532633939666666366462333063653431376230
30353864646161626566313265303237646630356439363433626565613464616161363039313532
36623337366130356138356335643563653238303362326166633638643265623833656566633334
3236323465363266653437326638313236333261363165636163
