$ANSIBLE_VAULT;1.1;AES256
63613630383364383739353462636430386663663339633763336139613562393663373661393031
3935343337333966326538373061623361343062386366370a653364306438316161623930393162
34333861353736646264313937633630373033646635656566386435343963366334636162356163
3538663231633933630a366664373939653133393234383530663261396461643766626137393663
32303830663032623132333062353164343037623735643438626565636434306135366462393438
32363064653863346365303933306538616533396439616433336137356165356461663734366464
65343464363965383364393733656464326436656461336435393663373336323461643938306431
36656236623038336232316166393631643030303664303935653165313239316331323634383539
38636432663864316365633934313837373530376637366562383435633431616137306265383932
61393234623537353030633666643138316363346539346539386566663436653966653431356565
37363036356336326437363231626632383066343637393835623866336436663435373866343036
65363464366133623864303837643266663161633439393031646633346563643939653465303063
33343762353834353463636262643531646534333062356432353966313632383439303961326532
33353366313564346162363266363932373731633633353663656334656237343932643534346262
32366238616264643937343639623634626539316565646562663864336163366361366264616662
31396139613837356139366365613139643732666632623865653436343830396264353066633564
33306333356630383033303536363737623537646432653136656166386666663063316636313838
31656333656638346131393566343566643330396539316363356163306663353034316134623866
35633466346434613133343735643239623761616163303131303363313435376137376534656664
62396535336264656266373963623630333733313239396333386435393830333833383935663238
38396366646265666662613762393932663739383634343535613166313532393838636530353634
30336339356538303038326166366465366462613065636339646436666538323638623435333132
653264636135653331313863373432396561
