---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-map.yml
  - external-secret.yml
  - namespace.yml
  - helm.yml
  - http-route.yml
  - push-secret.yml

configMapGenerator:
  - name: garage-helm-values
    files:
      - base-values.yml=values.yml

configurations:
  - kustomizeconfig.yml
