---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: garage-token-gen
  namespace: authentik
spec:
  length: 32
  allowRepeat: true
  noUpper: false
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: garage-admin-token
  namespace: garage
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: garage-token-gen
  template:
    type: Opaque
    data:
      token: "{{ .password }}"
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: k3s/garage/credentials
          property: token
