---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: loki-gateway
spec:
  parentRefs:
    - name: gateway-internal
      namespace: network
  rules:
    - matches:
        - path:
            type: Exact
            value: /loki/api/v1/push
      backendRefs:
        - name: loki-write
          port: 3100
    - matches:
        - path:
            type: PathPrefix
            value: /loki/api/v1/
      backendRefs:
        - name: loki-read
          port: 3100
