---
- name: Setup external resources
  import_playbook: setup_external.yml

- name: Setup dns server
  import_playbook: setup_dns_server.yml

- name: Setup ntp server
  import_playbook: setup_ntp_server.yml

- name: Setup vault
  import_playbook: setup_vault.yml

- name: Setup OIDC endpoint
  import_playbook: setup_oidc.yml

- name: Setup K3s cluster
  import_playbook: setup_k3s_cluster.yml
