---
- name: Setup external resources
  import_playbook: setup_external.yml

- name: Setup dns server
  import_playbook: setup_dns_server.yml

- name: Setup ntp server
  import_playbook: setup_ntp_server.yml

- name: Setup vault
  import_playbook: setup_vault.yml

- name: Setup k3s master
  import_playbook: setup_k3s_master.yml

- name: Setup k3s agent
  import_playbook: setup_k3s_agent.yml
