---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - cluster-role-binding.yml
  - cluster-secret-store.yml
  - helm.yml

configMapGenerator:
  - name: external-secrets-helm-values
    files:
      - base-values.yml=values.yml

configurations:
  - kustomizeconfig.yml
