---
vault_user: "openbao"
vault_user_dir: "/home/{{ vault_user }}"

vault_config_dir: "/etc/openbao"
vault_tls_dir: "{{ vault_config_dir }}/tls"

vault_opt_dir: "/opt/openbao"
vault_storage_dir: "{{ vault_opt_dir }}/data"

vault_pkcs11_lib: "/usr/lib/{{ ansible_architecture }}-linux-gnu/pkcs11/opensc-pkcs11.so"
vault_token_label: "vault"
