---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ansible-k3s-oidc-provider
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: oidc_provider_arn
      remoteRef:
        key: ansible/k3s/oidc
        property: provider_arn
