---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm.yml

configMapGenerator:
  - name: flux-instance-helm-values
    files:
      - base-values.yml=values.yml

configurations:
  - kustomizeconfig.yml
