---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: external-secrets-tf
spec:
  path: ./k8s/platform/external-secrets/app/tf
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  approvePlan: auto
